#if defined(LANGUAGE_EN_US)
  #define TXT_BACK "Back"
  #define TXT_CLOCK "Clock"
  #define TXT_SETTINGS "Settings"
  #define TXT_NEVER "Never"
  #define TXT_SEC "seconds"
  #define TXT_MIN	"minutes"
  #define TXT_AUTO_DIM "SET AUTO DIM TIME"
  #define TXT_SET_BRIGHT "SET BRIGHTNESS"
  #define TXT_BATT_INFO "Battery Info"
  #define TXT_BRIGHT "Brightness"
  #define TXT_SET_CLOCK "Set Clock"
  #define TXT_ROTATION "Rotation"
  #define TXT_ABOUT "About"
  #define TXT_REBOOT "Reboot"
  #define TXT_CLR_SETTINGS "Clear Settings"
  #define TXT_CLRING_SETTINGS "Restoring Default\nSettings..."
  #define TXT_RIGHT "Right"
  #define TXT_LEFT "Left"
  #define TXT_BATT "Battery: "
  #define TXT_EXIT "Press any key to exit"
  #define TXT_RG_AMERICAS "Region:\nAmericas / Asia\n"
  #define TXT_RG_EMEA "Region: EMEA"
  #define TXT_SEL_GO_PAUSE "Select: Go/Pause"
  #define TXT_SEL_EXIT "Next: Exit"
  #define TXT_TRIG_TV "triggered TVBG"
  #define TXT_MN_AMERICA "Americas / Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Region"
  #define TXT_FK_GP "Front Key: Go/Pause"
  #define TXT_SET_HOUR "SET HOUR"
  #define TXT_SET_MIN "SET MINUTE"
  #define TXT_ADV "Advertising:\n"  
  #define TXT_SP_RND "Swift Pair Random"
  #define TXT_SEL_EXIT2 "\n\nNext: Exit"
  #define TXT_BT_SPAM "BT Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM " Combined BT Spam"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transfer Number"
  #define TXT_AJ_TV_COLOR "TV Color Balance"
  #define TXT_STP_NW_PH "Setup New Phone"
  #define TXT_SA_ADV "SourApple Advertisement: "
  #define TXT_SP_ADV "SwiftPair Advertisement: '%s' - "
  #define TXT_AD_SPAM_ADV "Android Spam Advertisement: "
  #define TXT_AJ_ADV "AppleJuice Advertisement: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - Random SSIDs\n"
  #define TXT_WF_SCAN "Scan Wifi"
  #define TXT_WF_SPAM_FUN "Spam Funny"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Random"
  #define TXT_WF_RESCAN "[RESCAN]"
  #define TXT_WF_OPEN "Open"
  #define TXT_WF_CHANN "Chan : %d\n"
  #define TXT_WF_CRYPT "Crypt: %s\n"
  #define TXT_SEL_BACK "\nNext: Back\n"
  #define TXT_HOLD_CLONE "Hold Select: Clone\n"
  #define TXT_WF_SCN "WiFi Scan"
  #define TXT_WF_SCNING "Scanning..."
  #define TXT_INST_NXT "Next: Down Arrow"
  #define TXT_INST_PRV "Prev: Up Arrow"
  #define TXT_INST_SEL "Sel : Enter or ->"
  #define TXT_INST_HOME "Home: Esc   or <- "
  #define TXT_INST_PRSS_KEY "         Press a key"
  #define TXT_STK_NXT "Next: Side Button"
  #define TXT_STK_SEL "Sel : M5 Button"
  #define TXT_STK_HOME "Home: Power Button"

#endif

#if defined(LANGUAGE_PT_BR)
  #define TXT_BACK "Voltar"
  #define TXT_CLOCK "Relogio"
  #define TXT_SETTINGS "Configuracoes"
  #define TXT_NEVER "Nunca"
  #define TXT_SEC "segundos"
  #define TXT_MIN	"minutos"
  #define TXT_AUTO_DIM "AJUSTAR LUZ DE FUNDO"
  #define TXT_SET_BRIGHT "BRILHO DA TELA"
  #define TXT_BATT_INFO "Estado da Bateria"
  #define TXT_BRIGHT "Brilho"
  #define TXT_SET_CLOCK "Ajustar Relogio"
  #define TXT_ROTATION "Rotacao"
  #define TXT_ABOUT "Sobre"
  #define TXT_REBOOT "Reiniciar M5"
  #define TXT_CLR_SETTINGS "Resetar Ajustes"
  #define TXT_CLRING_SETTINGS "Aplicando Ajustes\nPadrao..."
  #define TXT_RIGHT "Direita"
  #define TXT_LEFT "Esquerda"
  #define TXT_BATT "Bateria: "
  #define TXT_EXIT "Pressione qualquer tecla para sair"
  #define TXT_RG_AMERICAS "Regiao:\nAmericas / Asia\n"
  #define TXT_RG_EMEA "Regiao: EMEA"
  #define TXT_SEL_GO_PAUSE "Ok: Iniciar/Parar"
  #define TXT_SEL_EXIT "Seta 'v' : Sair"
  #define TXT_TRIG_TV "TVBG em funcionamento..."
  #define TXT_MN_AMERICA "Americas/Asia"
  #define TXT_MN_EMEA "EU/MidEast/Africa"
  #define TXT_REGION "Regiao"
  #define TXT_FK_GP "Botao Frontal:Iniciar/Pausar"
  #define TXT_SET_HOUR "AJUSTAR HORA"
  #define TXT_SET_MIN "AJUSTAR MINUTO"
  #define TXT_ADV "Aviso:\n"  
  #define TXT_SP_RND "Swift Pair Aleatorio"
  #define TXT_SEL_EXIT2 "\n\nProx: Sair"
  #define TXT_BT_SPAM "Bluetooth Spam"
  #define TXT_SA_CRASH "SourApple Crash"
  #define TXT_CMB_BT_SPAM "BT Spam Combinado"
  #define TXT_AD_SPAM "Android Spam"
  #define TXT_AJ_TRANSF_NM "Transferir Numero"
  #define TXT_AJ_TV_COLOR "Balanco de Cor TV"
  #define TXT_STP_NW_PH "Novo Aparelho"
  #define TXT_SA_ADV "Aviso SourApple: "
  #define TXT_SP_ADV "Aviso SwiftPair: '%s' - "
  #define TXT_AD_SPAM_ADV "Aviso Android Spam: "
  #define TXT_AJ_ADV "Aviso AppleJuice: "
  #define TXT_WF_SP "WiFi Spam"
  #define TXT_RND_SSID " - SSIDs Aleatorios\n"
  #define TXT_WF_SCAN "Escanear Wifi"
  #define TXT_WF_SPAM_FUN "Spam Engracado"
  #define TXT_WF_SPAM_RR "Spam Rickroll"
  #define TXT_WF_SPAM_RND "Spam Aleatorio"
  #define TXT_WF_RESCAN "[RESCANEAR]"
  #define TXT_WF_OPEN "Aberto"
  #define TXT_WF_CHANN "Canal: %d\n"
  #define TXT_WF_CRYPT "Cripto: %s\n"
  #define TXT_SEL_BACK "\nProx: Voltar\n"
  #define TXT_HOLD_CLONE "Segurar Ok: Clonar\n"
  #define TXT_WF_SCN "Escanear \n   Wifi"
  #define TXT_WF_SCNING "Escaneando..."
  #define TXT_INST_NXT "Prox: Seta v"
  #define TXT_INST_PRV "Anterior: Seta ^"
  #define TXT_INST_SEL "Sel : Ok ou Seta >"
  #define TXT_INST_HOME "Home: Esc ou Seta <"
  #define TXT_INST_PRSS_KEY "Pressione uma tecla"
  #define TXT_STK_NXT "Prox: Botao do Lado"
  #define TXT_STK_SEL "Sel : Botao M5"
  #define TXT_STK_HOME "Home: Botao Power"
#endif