---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Arduino-CI/action@stable-1.x
        # env:

  compile_sketch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # For more information: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          # The default is to compile for the Arduino Uno board. If you want to compile for other boards, use the `fqbn` input.
          # fqbn:
          sketch-paths: |
            - ./
            - ./demo_sketch
          libraries: |
            -

