---
name: Demo Compile Sketch

on:
  push:
    branches:
      - main
    # paths:
    #   - 'demo_sketch/**'
  pull_request:
    branches:
      - main
  

jobs:
  compile_demo_sketch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform
        run: |
          set -x
          # arduino-cli core install esp32:esp32
          arduino-cli core install m5stack:esp32 --additional-urls "file:///${PWD}/package_m5stack_index.json"

          arduino-cli core search m5stack
          arduino-cli board listall

          arduino-cli lib install M5Cardputer --log-level warn --verbose
          arduino-cli lib install IRRemoteESP8266 --log-level warn --verbose 

      - name: Compile Sketch
        run: arduino-cli compile --fqbn m5stack:esp32:m5stack_cardputer -e ./demo_sketch
      
      - name: List all files
        run: |
          set -x
          pwd
          tree
        
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          # path: /home/runner/work/m5stick-nemo/m5stick-nemo/demo_sketch/build/m5stack:esp32:m5stack_cardputer/demo_sketch.ino.bin
          path: demo_sketch/build/m5stack.esp32.m5stack_cardputer/demo_sketch.ino.bin
          name: demo_sketch_${{ github.run_number }}
          # if-no-files-found: error
